import Hero from '@/components/marketing/hero';
import EmptyState from '@atlaskit/empty-state';
import { Alert, Button, Layout, notification, Result, Space } from 'antd';
import Head from 'next/head';
const { Header, Footer, Sider, Content } = Layout;

export default function Home() {
  const [api, contextHolder] = notification.useNotification();
  const openNotification = () => {
    notification.open({
      message: '{UserName} has been invited',
      description:
        'This notification content should be powered by us, along with tracking the metrics of how it performs with impressions and clicks!',
      onClick: () => {
        console.log('Notification Clicked!');
      },
    });
  };

  return (
    <>
      <Space direction="vertical" style={{ width: '100%' }} size={[0, 48]}>
        <Header>
          <Head>
            <title>HappyPath Demo Site</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </Header>
        <Content style={{ padding: '0 50px' }}>
          <Hero />

          <p>
            <h4>Get Started:</h4>
            <code>npm i @happypath/emptystates</code>
          </p>

          {/* NOTIFICATION EXAMPLE */}
          <Button type="primary" onClick={openNotification}>
            Open the notification box
          </Button>
          {/* END NOTIFICATION EXAMPLE */}

          {/* Empty state - replace with ours! */}
          <EmptyState
            header="hello empty state!"
            description="This is of the empty state from atlassian component"
            primaryAction={
              <Button type="primary">Works with existing buttons</Button>
            }
          />
          {/* ALERT */}
          <Alert
            message="Hi {Taylor}, you are getting close to your monthly credit limit"
            description="You can upgrade to the `{ProPlan.name}` plan and you will be able to get `{ProPlan.TotalCredits}` credits per month. Wowza!"
            type="warning"
            showIcon
            closable
            action={
              <Space direction="horizontal">
                <Button size="small" type="primary">
                  <a href="#custom-action-link">Learn more</a>
                </Button>
                <Button size="small" danger type="ghost">
                  <a
                    href="https://calendly.com/synthesize"
                    target={'_blank'}
                    rel="noreferrer"
                  >
                    Schedule a walk-through
                  </a>
                </Button>
              </Space>
            }
          />

          {/* `RESULT` from ant.design */}
          <Result
            status="success"
            title="Successfully Purchased Cloud Server ECS!"
            subTitle="Order number: 2017182818828182881 Cloud server configuration takes 1-5 minutes, please wait."
            extra={[
              <Button type="primary" key="console">
                Go Console
              </Button>,
              <Button key="buy">Buy Again</Button>,
            ]}
          />
        </Content>
        <Footer style={{ textAlign: 'center' }}>Synthesize Inc.</Footer>
      </Space>
    </>
  );
}
